export default [
  { hasWatched: false, order: '1', airNumber: '216', title: 'Cat and Mouse' },
  { hasWatched: false, order: '2', airNumber: '116', title: 'Hidden Enemy' },
  {
    hasWatched: false,
    order: '',
    airNumber: 'T',
    title: 'The Clone Wars theatrical release',
  },
  { hasWatched: false, order: '3', airNumber: '301', title: 'Clone Cadets' },
  { hasWatched: false, order: '4', airNumber: '303', title: 'Supply Lines' },
  { hasWatched: false, order: '5', airNumber: '101', title: 'Ambush' },
  {
    hasWatched: false,
    order: '6',
    airNumber: '102',
    title: 'Rising Malevolence',
  },
  {
    hasWatched: false,
    order: '7',
    airNumber: '103',
    title: 'Shadow of Malevolence',
  },
  {
    hasWatched: false,
    order: '8',
    airNumber: '104',
    title: 'Destroy Malevolence',
  },
  { hasWatched: false, order: '9', airNumber: '105', title: 'Rookies' },
  {
    hasWatched: false,
    order: '10',
    airNumber: '106',
    title: 'Downfall of a Droid',
  },
  {
    hasWatched: false,
    order: '11',
    airNumber: '107',
    title: 'Duel of the Droids',
  },
  { hasWatched: false, order: '12', airNumber: '108', title: 'Bombad Jedi' },
  {
    hasWatched: false,
    order: '13',
    airNumber: '109',
    title: 'Cloak of Darkness',
  },
  {
    hasWatched: false,
    order: '14',
    airNumber: '110',
    title: 'Lair of Grievous',
  },
  { hasWatched: false, order: '15', airNumber: '111', title: 'Dooku Captured' },
  {
    hasWatched: false,
    order: '16',
    airNumber: '112',
    title: 'The Gungan General',
  },
  { hasWatched: false, order: '17', airNumber: '113', title: 'Jedi Crash' },
  {
    hasWatched: false,
    order: '18',
    airNumber: '114',
    title: 'Defenders of Peace',
  },
  { hasWatched: false, order: '19', airNumber: '115', title: 'Trespass' },
  {
    hasWatched: false,
    order: '20',
    airNumber: '117',
    title: 'Blue Shadow Virus',
  },
  {
    hasWatched: false,
    order: '21',
    airNumber: '118',
    title: 'Mystery of a Thousand Moons',
  },
  {
    hasWatched: false,
    order: '22',
    airNumber: '119',
    title: 'Storm over Ryloth',
  },
  {
    hasWatched: false,
    order: '23',
    airNumber: '120',
    title: 'Innocents of Ryloth',
  },
  {
    hasWatched: false,
    order: '24',
    airNumber: '121',
    title: 'Liberty on Ryloth',
  },
  { hasWatched: false, order: '25', airNumber: '201', title: 'Holocron Heist' },
  { hasWatched: false, order: '26', airNumber: '202', title: 'Cargo of Doom' },
  {
    hasWatched: false,
    order: '27',
    airNumber: '203',
    title: 'Children of the Force',
  },
  { hasWatched: false, order: '28', airNumber: '217', title: 'Bounty Hunters' },
  {
    hasWatched: false,
    order: '29',
    airNumber: '218',
    title: 'The Zillo Beast',
  },
  {
    hasWatched: false,
    order: '30',
    airNumber: '219',
    title: 'The Zillo Beast Strikes Back',
  },
  { hasWatched: false, order: '31', airNumber: '204', title: 'Senate Spy' },
  {
    hasWatched: false,
    order: '32',
    airNumber: '205',
    title: 'Landing at Point Rain',
  },
  {
    hasWatched: false,
    order: '33',
    airNumber: '206',
    title: 'Weapons Factory',
  },
  {
    hasWatched: false,
    order: '34',
    airNumber: '207',
    title: 'Legacy of Terror',
  },
  { hasWatched: false, order: '35', airNumber: '208', title: 'Brain Invaders' },
  {
    hasWatched: false,
    order: '36',
    airNumber: '209',
    title: 'Grievous Intrigue',
  },
  { hasWatched: false, order: '37', airNumber: '210', title: 'The Deserter' },
  {
    hasWatched: false,
    order: '38',
    airNumber: '211',
    title: 'Lightsaber Lost',
  },
  {
    hasWatched: false,
    order: '39',
    airNumber: '212',
    title: 'The Mandalore Plot',
  },
  {
    hasWatched: false,
    order: '40',
    airNumber: '213',
    title: 'Voyage of Temptation',
  },
  {
    hasWatched: false,
    order: '41',
    airNumber: '214',
    title: 'Duchess of Mandalore',
  },
  { hasWatched: false, order: '42', airNumber: '220', title: 'Death Trap' },
  { hasWatched: false, order: '43', airNumber: '221', title: 'R2 Come Home' },
  {
    hasWatched: false,
    order: '44',
    airNumber: '222',
    title: 'Lethal Trackdown',
  },
  { hasWatched: false, order: '45', airNumber: '305', title: 'Corruption' },
  { hasWatched: false, order: '46', airNumber: '306', title: 'The Academy' },
  { hasWatched: false, order: '47', airNumber: '307', title: 'Assassin' },
  { hasWatched: false, order: '48', airNumber: '302', title: 'ARC Troopers' },
  {
    hasWatched: false,
    order: '49',
    airNumber: '304',
    title: 'Sphere of Influence',
  },
  { hasWatched: false, order: '50', airNumber: '308', title: 'Evil Plans' },
  { hasWatched: false, order: '51', airNumber: '122', title: 'Hostage Crisis' },
  { hasWatched: false, order: '52', airNumber: '309', title: 'Hunt for Ziro' },
  {
    hasWatched: false,
    order: '53',
    airNumber: '310',
    title: 'Heroes on Both Side',
  },
  {
    hasWatched: false,
    order: '54',
    airNumber: '311',
    title: 'Pursuit of Peace',
  },
  { hasWatched: false, order: '55', airNumber: '215', title: 'Senate Murders' },
  { hasWatched: false, order: '56', airNumber: '312', title: 'Nightsisters' },
  { hasWatched: false, order: '57', airNumber: '313', title: 'Monster' },
  {
    hasWatched: false,
    order: '58',
    airNumber: '314',
    title: 'Witches of the Mist',
  },
  { hasWatched: false, order: '59', airNumber: '315', title: 'Overlords' },
  {
    hasWatched: false,
    order: '60',
    airNumber: '316',
    title: 'Altar of Mortis',
  },
  {
    hasWatched: false,
    order: '61',
    airNumber: '317',
    title: 'Ghosts of Mortis',
  },
  { hasWatched: false, order: '62', airNumber: '318', title: 'The Citadel' },
  { hasWatched: false, order: '63', airNumber: '319', title: 'Counter Attack' },
  { hasWatched: false, order: '64', airNumber: '320', title: 'Citadel Rescue' },
  { hasWatched: false, order: '65', airNumber: '321', title: 'Padawan Lost' },
  { hasWatched: false, order: '66', airNumber: '322', title: 'Wookiee Hunt' },
  { hasWatched: false, order: '67', airNumber: '401', title: 'Water War' },
  { hasWatched: false, order: '68', airNumber: '402', title: 'Gungan Attack' },
  { hasWatched: false, order: '69', airNumber: '403', title: 'Prisoners' },
  { hasWatched: false, order: '70', airNumber: '404', title: 'Shadow Warrior' },
  { hasWatched: false, order: '71', airNumber: '405', title: 'Mercy Mission' },
  { hasWatched: false, order: '72', airNumber: '406', title: 'Nomad Droids' },
  {
    hasWatched: false,
    order: '73',
    airNumber: '407',
    title: 'Darkness on Umbara',
  },
  { hasWatched: false, order: '74', airNumber: '408', title: 'The General' },
  {
    hasWatched: false,
    order: '75',
    airNumber: '409',
    title: 'Plan of Dissent',
  },
  {
    hasWatched: false,
    order: '76',
    airNumber: '410',
    title: 'Carnage of Krell',
  },
  { hasWatched: false, order: '77', airNumber: '411', title: 'Kidnapped' },
  {
    hasWatched: false,
    order: '78',
    airNumber: '412',
    title: 'Slaves of the Republic',
  },
  {
    hasWatched: false,
    order: '79',
    airNumber: '413',
    title: 'Escape from Kadavo',
  },
  {
    hasWatched: false,
    order: '80',
    airNumber: '414',
    title: 'A Friend In Need',
  },
  { hasWatched: false, order: '81', airNumber: '415', title: 'Deception' },
  {
    hasWatched: false,
    order: '82',
    airNumber: '416',
    title: 'Friends and Enemies',
  },
  { hasWatched: false, order: '83', airNumber: '417', title: 'The Box' },
  {
    hasWatched: false,
    order: '84',
    airNumber: '418',
    title: 'Crisis on Naboo',
  },
  { hasWatched: false, order: '85', airNumber: '419', title: 'Massacre' },
  { hasWatched: false, order: '86', airNumber: '420', title: 'Bounty' },
  { hasWatched: false, order: '87', airNumber: '421', title: 'Brothers' },
  { hasWatched: false, order: '88', airNumber: '422', title: 'Revenge' },
  {
    hasWatched: false,
    order: '89',
    airNumber: '502',
    title: 'A War on Two Fronts',
  },
  { hasWatched: false, order: '90', airNumber: '503', title: 'Front Runners' },
  { hasWatched: false, order: '91', airNumber: '504', title: 'The Soft War' },
  { hasWatched: false, order: '92', airNumber: '505', title: 'Tipping Points' },
  { hasWatched: false, order: '93', airNumber: '506', title: 'The Gathering' },
  {
    hasWatched: false,
    order: '94',
    airNumber: '507',
    title: 'A Test of Strength',
  },
  {
    hasWatched: false,
    order: '95',
    airNumber: '508',
    title: 'Bound for Rescue',
  },
  {
    hasWatched: false,
    order: '96',
    airNumber: '509',
    title: 'A Necessary Bond',
  },
  { hasWatched: false, order: '97', airNumber: '510', title: 'Secret Weapons' },
  {
    hasWatched: false,
    order: '98',
    airNumber: '511',
    title: 'A Sunny Day in the Void',
  },
  {
    hasWatched: false,
    order: '99',
    airNumber: '512',
    title: 'Missing in Action',
  },
  {
    hasWatched: false,
    order: '100',
    airNumber: '513',
    title: 'Point of No Return',
  },
  { hasWatched: false, order: '101', airNumber: '501', title: 'Revival' },
  { hasWatched: false, order: '102', airNumber: '514', title: 'Eminence' },
  {
    hasWatched: false,
    order: '103',
    airNumber: '515',
    title: 'Shades of Reason',
  },
  { hasWatched: false, order: '104', airNumber: '516', title: 'The Lawless' },
  { hasWatched: false, order: '105', airNumber: '517', title: 'Sabotage' },
  {
    hasWatched: false,
    order: '106',
    airNumber: '518',
    title: 'The Jedi Who Knew Too Much',
  },
  {
    hasWatched: false,
    order: '107',
    airNumber: '519',
    title: 'To Catch a Jedi',
  },
  {
    hasWatched: false,
    order: '108',
    airNumber: '520',
    title: 'The Wrong Jedi',
  },
  { hasWatched: false, order: '109', airNumber: '601', title: 'The Unknown' },
  { hasWatched: false, order: '110', airNumber: '602', title: 'Conspiracy' },
  { hasWatched: false, order: '111', airNumber: '603', title: 'Fugitive' },
  { hasWatched: false, order: '112', airNumber: '604', title: 'Orders' },
  { hasWatched: false, order: '113', airNumber: '605', title: 'An Old Friend' },
  {
    hasWatched: false,
    order: '114',
    airNumber: '606',
    title: 'The Rise of Clovis',
  },
  {
    hasWatched: false,
    order: '115',
    airNumber: '607',
    title: 'Crisis at the Heart',
  },
  {
    hasWatched: false,
    order: '116',
    airNumber: '608',
    title: 'The Disappeared',
  },
  {
    hasWatched: false,
    order: '117',
    airNumber: '609',
    title: 'The Disappeared: Pt. II',
  },
  { hasWatched: false, order: '118', airNumber: '610', title: 'The Lost One' },
  { hasWatched: false, order: '119', airNumber: '611', title: 'Voices' },
  { hasWatched: false, order: '120', airNumber: '612', title: 'Destiny' },
  { hasWatched: false, order: '121', airNumber: '613', title: 'Sacrifice' },
  {
    hasWatched: false,
    order: '122',
    airNumber: '705',
    title: 'Gone with a Trace',
  },
  { hasWatched: false, order: '123', airNumber: '706', title: 'Deal No Deal' },
  {
    hasWatched: false,
    order: '124',
    airNumber: '707',
    title: 'Dangerous Debt',
  },
  {
    hasWatched: false,
    order: '125',
    airNumber: '708',
    title: 'Together Again',
  },
  { hasWatched: false, order: '126', airNumber: '701', title: 'The Bad Batch' },
  {
    hasWatched: false,
    order: '127',
    airNumber: '702',
    title: 'A Distant Echo',
  },
  {
    hasWatched: false,
    order: '128',
    airNumber: '703',
    title: 'On the Wings of Keeradaks',
  },
  {
    hasWatched: false,
    order: '129',
    airNumber: '704',
    title: 'Unfinished Business',
  },
  {
    hasWatched: false,
    order: '130',
    airNumber: '709',
    title: 'Old Friends Not Forgotten',
  },
  {
    hasWatched: false,
    order: '131',
    airNumber: '710',
    title: 'The Phantom Apprentice',
  },
  { hasWatched: false, order: '132', airNumber: '711', title: 'Shattered' },
  {
    hasWatched: false,
    order: '133',
    airNumber: '712',
    title: 'Victory and Death',
  },
]
